### ISSUE TITLE
Code/design review: stylesheet linken

### ISSUE THREAD

**Issue by ambersr** [miel775/look-and-feel-corporate-identity#2]
Probeer nog even te kijken hoe je de stylesheet op de juiste manier kan linken. 

Kijk bijvoorbeeld bij mijn HTML: https://github.com/ambersr/look-and-feel-corporate-identity/blob/main/index.html

Zodra je de stylesheet juist gelinkt hebt maak dan gebruik van de custom properties:

```
h1 {
color: var(..)
}
```

@saschavanvliet
@reyrey-https

**Comment by miel775** [comment]
https://github.com/miel775/look-and-feel-corporate-identity/commit/7fbc41d6a365f299b6c21d6b7e20c35863404277
