### ISSUE TITLE
Je linkt wel een andere stylesheet, maar gebruikt alleen je index sheet.

### ISSUE THREAD

**Issue by rutgerkock** [miel775/look-and-feel-corporate-identity#3]
Het idee is dat je een gezamelijke stylesheet gebruikt met een algemene setup, je hebt nu een eigen bestand met een kopie van algemene styling, met daaronder je eigen styling.
https://github.com/miel775/look-and-feel-corporate-identity/blob/efadae7b85668ec0ebbbc6c60096b643ed46a24d/index.html#L7-L8

**Comment by miel775** [comment]
opgelost[
](https://github.com/miel775/look-and-feel-corporate-identity/commit/7fbc41d6a365f299b6c21d6b7e20c35863404277)
